### ISSUE TITLE
Seq.cov and Seq.covPopulation are missing

### ISSUE THREAD

**Issue by nhirschey** [fslaborg/FSharp.Stats#112]
**Is your feature request related to a problem? Please describe.**
The Seq.cov and Seq.covPopulation functions are missing. This appears to be an oversight rather than a deliberate decision because the covariance documentation says that they are there, see code below the references here https://fslab.org/FSharp.Stats/Covariance.html. 

You can see the source where it is explicitly commented out: https://github.com/fslaborg/FSharp.Stats/blob/53e33327d3b07840c9b5ad7dab2c9db71cc509ec/src/FSharp.Stats/Seq.fs#L533 

I'm guessing that it was commented out during an api rewrite and then forgotten, as 
1. the new documentation says the new names should be Seq.cov and Seq.covPopulation (rather than Seq.covariance in the old code)
2. the cov Calculation in [Correlation.Seq.pearson](https://github.com/fslaborg/FSharp.Stats/blob/53e33327d3b07840c9b5ad7dab2c9db71cc509ec/src/FSharp.Stats/Correlation.fs#L58) appears like it's newer. 

**Describe the solution you'd like**
It would be nice to have access to Seq.cov, Seq.covPopulation, and Seq.covWeighted (if that's the best api naming scheme).

I could do a pull request copying code from Correlation.fs to Seq.fs, but before I do that I figured it's better to see what your plans are here.

**Comment by bvenn** [comment]
Hi @nhirschey,

I think the best way would be to move the implemented [Vector.cov](https://github.com/fslaborg/FSharp.Stats/blob/53e33327d3b07840c9b5ad7dab2c9db71cc509ec/src/FSharp.Stats/Vector.fs#L358) and Vector.covOfPopulation from `Vector.fs` to `Seq.fs`. Afterwards a `List.cov`, `Array.cov`, and `Vector.cov` can point to `Seq.cov`. 

I've noticed, that also a `covBy` functionality is missing. 

If you want, you can open a PR, otherwise I would take care of it.

**Comment by nhirschey** [comment]
This looks like a simple change using the Vector.cov code, so I can try to put together a pull request to help you guys out here.

**Comment by nhirschey** [comment]
Closing, functionality added with https://github.com/fslaborg/FSharp.Stats/pull/114
